"""
Django settings for ecom_prj project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from environs import Env
import os
from django.contrib import messages

env = Env()  
env.read_env()  

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&6z&2t9_i2!sfk0^5@g+2o8++q^gc=_aez&r_w&4q&d)_da%6d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*", ".ngrok-free.app"]
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1',
    'https://59b1-190-235-170-190.ngrok-free.app',
    'https://*.ngrok-free.app',
    'https://fastcart.up.railway.app'
]
# Opcionalmente, para asegurar el uso de HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.humanize',
    'django.contrib.staticfiles',
    
    'userauths',
    'store',
    'vendor',
    'customer',
    'blog',
    
    'anymail',
    'django_ckeditor_5',
    'captcha',
    'import_export'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecom_prj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'store.context.default',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecom_prj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

ANYMAIL = {
    "MAILGUN_API_KEY": os.environ.get("MAILGUN_API_KEY"),
    "MAILGUN_SENDER_DOMAIN": os.environ.get("MAILGUN_SENDER_DOMAIN"),
}

FROM_EMAIL = env("FROM_EMAIL")
EMAIL_BACKEND = env("EMAIL_BACKEND")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")
SERVER_EMAIL = env("SERVER_EMAIL")

LOGOUT_REDIRECT_URL="userauths:sign-in"
LOGIN_URL="userauths:sign-in"

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = "/media/" #website.com/media/

MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'userauths.User'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

PAYPPAL_CLIENT_ID = env('PAYPPAL_CLIENT_ID')
PAYPPAL_SECRET_ID = env('PAYPPAL_SECRET_ID')

STTRIPE_PUBLIC_KEY = env('STTRIPE_PUBLIC_KEY')
STTRIPE_SECRET_KEY = env('STTRIPE_SECRET_KEY')

PAYSTTACK_PUBLIC_KEY = env('PAYSTTACK_PUBLIC_KEY')
PAYSTTACK_PRIVATE_KEY = env('PAYSTTACK_PRIVATE_KEY')

FLUTTERWAVEE_PUBLIC_KEY = env("FLUTTERWAVEE_PUBLIC_KEY")
FLUTTERWAVEE_PRIVATE_KEY = env("FLUTTERWAVEE_PRIVATE_KEY")

RECAPTCHA_PUBLIC_KEY = env("DJANGO_RECAPTCHA_PUBLIC_KEY")
RECAPTCHA_PRIVATE_KEY = env("DJANGO_RECAPTCHA_PRIVATE_KEY")

MESSAGES_TAGS = {
    messages.ERROR: "error"
}

JAZZMIN_SETTINGS = {
    "site_title": "Tienda Rico",
    "site_header": "Tienda Rico",
    "site_brand": "Tienda Rico",
    "welcome_sign": "Bienvenido/a a Rico",
    "copyright": "© 2025 Tienda Rico",
    
    # Logo e icono del sitio
    "site_icon": None,  # Usa el ícono por defecto de Jazzmin
    "site_logo": None,  # No se mostrará un logo en la barra lateral
    "login_logo": None,  # No se mostrará un logo en la pantalla de login
    "login_background": None,

    # Personalización del Tema
    "theme": "darkly",  # Otras opciones: "cosmo", "flatly", "sandstone", "solar", "cyborg"
    
    # Barra de Navegación y Sidebar
    "fixed_navbar": True,
    "show_sidebar": True,
    "navigation_expanded": False,  # Sidebar minimizado por defecto

    # Organización del menú
    "order_with_respect_to": [
        "store", "store.product", "store.cartorder", "store.cartorderitem",
        "store.cart", "store.category", "store.brand", "store.productfaq",
        "store.review", "vendor.Coupon", "vendor.DeliveryCouriers",
        "userauths", "userauths.user", "userauths.profile",
        "donations", "blog", 'newsfeed', "contacts", "addon",
    ],

    # Iconos para cada modelo
    "icons": {
        "admin.LogEntry": "fas fa-file",
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "userauths.User": "fas fa-user",
        "userauths.Profile": "fas fa-address-card",
        "donations.Donation": "fas fa-hand-holding-usd",
        "donations.Payment": "fas fa-credit-card",
        "newsfeed.Newsletter": "fas fa-envelope",
        "contacts.Inquiry": "fas fa-phone",
        "addon.BasicAddon": "fas fa-cog",
        
        "store.Product": "fas fa-th",
        "store.CartOrder": "fas fa-shopping-cart",
        "store.Cart": "fas fa-cart-plus",
        "store.CartOrderItem": "fas fa-shopping-basket",
        "store.Brand": "fas fa-check-circle",
        "store.productfaq": "fas fa-question",
        "store.Review": "fas fa-star fa-beat",
        "store.Category": "fas fa-tag",
        "store.Notification": "fas fa-bell",
        "store.StoreSettings": "fas fa-tools",
        "store.Coupon": "fas fa-ticket-alt",
        "store.Gallery": "fas fa-images",
        "store.MensajeContacto": "fas fa-envelope-open-text",
        "store.Order": "fas fa-shopping-bag",
        "store.OrderItem": "fas fa-box-open",
        "store.Slider": "fas fa-sliders-h",
        "store.AboutUs": "fas fa-info-circle",
        "store.VariantItem": "fas fa-th-list",
        "store.Variant": "fas fa-palette",
        "store.CategoryPost": "fas fa-folder",  
        "store.Tag": "fas fa-tags",  
        "store.BlogPost": "fas fa-newspaper",  
        "store.BlogComment": "fas fa-comments",  
        "store.Subscriber": "fas fa-check-circle", 
        "store.PrivacyPolicy": "fas fa-file-signature",
        "store.TermsOfService": "fas fa-file-signature",
        
        "customer.Address": "fas fa-location-arrow",
        "customer.Wishlist": "fas fa-heart",
        "customer.Notifications": "fas fa-bell",
        
        "vendor.DeliveryCouriers": "fas fa-truck",
        "vendor.Coupon": "fas fa-percentage",
        "vendor.Vendor": "fas fa-store",
        "vendor.Payout": "fas fa-credit-card",
        "vendor.BankAccount": "fas fa-university",
        
        "addons.BecomeAVendor": "fas fa-user-plus",
        "addons.AboutUS": "fas fa-users",
    },

    # Iconos por defecto
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-arrow-circle-right",

    # Personalización de la Interfaz
    "changeform_format": "vertical_tabs",
    "changeform_format_overrides": {
        "store.Product": "horizontal_tabs",
        "auth.user": "collapsible",
    },

    # Accesos rápidos en la barra superior
    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Añadir Producto", "url": "admin:store_product_add", "permissions": ["store.add_product"]},
    ],

    # Atajos en el Dashboard
    "custom_links": {
        "store": [
            {"name": "Añadir Producto", "url": "admin:store_product_add", "icon": "fas fa-plus-circle", "permissions": ["store.add_product"]},
            {"name": "Ver Pedidos", "url": "admin:store_order_changelist", "icon": "fas fa-shopping-bag"},
        ],
    },

    # Panel de control personalizado
    "custom_dashboard": "admin_dashboard.html",

    # Permisos personalizados
    "permissions": {
        "store.Product": ["add", "change", "delete"],
        "store.Order": ["view", "change"],
    },

    # Mostrar constructor de UI (opcional)
    "show_ui_builder": True,
}



customColorPalette = [
    {"color": "hsl(4, 90%, 58%)", "label": "Red"},
    {"color": "hsl(340, 82%, 52%)", "label": "Pink"},
    {"color": "hsl(291, 64%, 42%)", "label": "Purple"},
    {"color": "hsl(262, 52%, 47%)", "label": "Deep Purple"},
    {"color": "hsl(231, 48%, 48%)", "label": "Indigo"},
    {"color": "hsl(207, 90%, 54%)", "label": "Blue"},
]

CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote",
            "imageUpload"
        ],
    },
    "comment": {
        "language": {"ui": "es", "content": "es"},
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote",
        ],
    },
    "extends": {
        "language": "es",
        "blockToolbar": [
            "paragraph",
            "heading1",
            "heading2",
            "heading3",
            "|",
            "bulletedList",
            "numberedList",
            "|",
            "blockQuote",
        ],
        "toolbar": [
            # "heading",
            # "codeBlock",
            # "|",
            # "outdent",
            # "indent",
            # "|",
            "bold",
            "italic",
            "underline",
            "|",
            "link",
            "strikethrough",
            "code",
            "subscript",
            "superscript",
            "highlight",
            "|",
            "bulletedList",
            "numberedList",
            "todoList",
            "|",
            "blockQuote",
            "insertImage",
            "|",
            "fontSize",
            "fontFamily",
            "fontColor",
            "fontBackgroundColor",
            "mediaEmbed",
            "removeFormat",
            "insertTable",
            "sourceEditing",
        ],
        "image": {
            "toolbar": [
                "imageTextAlternative",
                "|",
                "imageStyle:alignLeft",
                "imageStyle:alignRight",
                "imageStyle:alignCenter",
                "imageStyle:side",
                "|",
                "toggleImageCaption",
                "|"
            ],
            "styles": [
                "full",
                "side",
                "alignLeft",
                "alignRight",
                "alignCenter",
            ],
        },
        "table": {
            "contentToolbar": [
                "tableColumn",
                "tableRow",
                "mergeTableCells",
                "tableProperties",
                "tableCellProperties",
            ],
            "tableProperties": {
                "borderColors": customColorPalette,
                "backgroundColors": customColorPalette,
            },
            "tableCellProperties": {
                "borderColors": customColorPalette,
                "backgroundColors": customColorPalette,
            },
        },
        "heading": {
            "options": [
                {
                    "model": "paragraph",
                    "title": "Paragraph",
                    "class": "ck-heading_paragraph",
                },
                {
                    "model": "heading1",
                    "view": "h1",
                    "title": "Heading 1",
                    "class": "ck-heading_heading1",
                },
                {
                    "model": "heading2",
                    "view": "h2",
                    "title": "Heading 2",
                    "class": "ck-heading_heading2",
                },
                {
                    "model": "heading3",
                    "view": "h3",
                    "title": "Heading 3",
                    "class": "ck-heading_heading3",
                },
            ]
        },
        "list": {
            "properties": {
                "styles": True,
                "startIndex": True,
                "reversed": True,
            }
        },
        "htmlSupport": {
            "allow": [
                {"name": "/.*/", "attributes": True, "classes": True, "styles": True}
            ]
        },
    },
}