# Generated by Django 4.2 on 2025-03-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_Type',
            field=models.CharField(blank=True, choices=[('Vendor', 'Proveedor'), ('Customer', 'Cliente')], default=None, max_length=255, null=True),
        ),
    ]
