# Generated by Django 4.2 on 2025-03-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Published', 'Publicado'), ('Draft', 'Borrador'), ('Disabled', 'Desactivado')], default='Published', max_length=50),
        ),
    ]
