# Generated by Django 4.2 on 2025-03-30 00:40

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace del Botón'),
        ),
        migrations.AddField(
            model_name='slider',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto del Botón'),
        ),
        migrations.AddField(
            model_name='slider',
            name='has_button',
            field=models.BooleanField(default=False, verbose_name='¿Tiene botón?'),
        ),
        migrations.AddField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='slider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='sliders/', verbose_name='Imagen del Slider'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=6, max_length=25, prefix='', unique=True, verbose_name='ID del Slider'),
        ),
    ]
