# Generated by Django 4.2 on 2025-03-30 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_categorypost_post_commentpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='commentpost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryPost',
        ),
        migrations.DeleteModel(
            name='CommentPost',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
