# Generated by Django 4.2 on 2025-03-30 21:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_commentpost_post_remove_commentpost_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_us/gallery/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción de la Imagen')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Galería de Imágenes',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripción General')),
                ('history', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Nuestra Historia')),
                ('mission', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Nuestra Misión')),
                ('vision', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Nuestra Visión')),
                ('values', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Nuestros Valores')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('main_image', models.ImageField(upload_to='about_us/', verbose_name='Imagen Principal')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video Institucional (YouTube)')),
                ('gallery_images', models.ManyToManyField(blank=True, to='store.aboutusgallery', verbose_name='Galería de Imágenes')),
            ],
            options={
                'verbose_name': 'Sobre Nosotros',
                'verbose_name_plural': 'Sección Sobre Nosotros',
            },
        ),
    ]
