# Generated by Django 4.2 on 2025-03-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_aboutusgallery_aboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='AboutUsGallery',
        ),
    ]
