# Generated by Django 4.2 on 2025-03-31 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_mensajecontacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storesettings',
            options={'verbose_name': 'Configuración', 'verbose_name_plural': 'Configuraciones'},
        ),
    ]
