# Generated by Django 4.2 on 2025-03-31 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_categorypost_tag_blogpost_blogcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorypost',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías de posts'},
        ),
    ]
