# Generated by Django 4.2 on 2025-03-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_categorypost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='short_content',
            field=models.TextField(blank=True, default='Sin resumen', null=True, verbose_name='Contenido corto'),
        ),
    ]
