# Generated by Django 4.2 on 2025-04-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='DEFAULT_FROM_EMAIL',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Predeterminado'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='DJANGO_RECAPTCHA_PRIVATE_KEY',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='reCAPTCHA Private Key'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='DJANGO_RECAPTCHA_PUBLIC_KEY',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='reCAPTCHA Public Key'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='EMAIL_BACKEND',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Backend de Correo'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='FLUTTERWAVEE_PRIVATE_KEY',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Flutterwave Private Key'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='FLUTTERWAVEE_PUBLIC_KEY',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Flutterwave Public Key'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='FROM_EMAIL',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo de Envío'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='MAILGUN_API_KEY',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mailgun API Key'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='MAILGUN_SENDER_DOMAIN',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mailgun Sender Domain'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='PAYPPAL_CLIENT_ID',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PayPal Client ID'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='PAYPPAL_SECRET_ID',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PayPal Secret ID'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='PAYSTTACK_PRIVATE_KEY',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Paystack Private Key'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='PAYSTTACK_PUBLIC_KEY',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Paystack Public Key'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='SERVER_EMAIL',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo del Servidor'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='STTRIPE_PUBLIC_KEY',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Public Key'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='STTRIPE_SECRET_KEY',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Secret Key'),
        ),
    ]
