# Generated by Django 4.2 on 2025-04-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='MERCADOPAGO_ACCESS_TOKEN',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mercado Pago Access Token'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='MERCADOPAGO_PUBLIC_KEY',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mercado Pago Public Key'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Paypal', 'Paypal'), ('Stripe', 'Stripe'), ('Flutterwave', 'Flutterwave'), ('Paystack', 'Paystack'), ('Mercado Pago', 'Mercado Pago')], default=None, max_length=100, null=True),
        ),
    ]
