# Generated by Django 4.2 on 2025-04-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_storesettings_mercadopago_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesettings',
            name='MERCADOPAGO_ACCESS_TOKEN',
        ),
        migrations.RemoveField(
            model_name='storesettings',
            name='MERCADOPAGO_PUBLIC_KEY',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Paypal', 'Paypal'), ('Stripe', 'Stripe'), ('Flutterwave', 'Flutterwave'), ('Paystack', 'Paystack')], default=None, max_length=100, null=True),
        ),
    ]
