# Generated by Django 4.2 on 2025-04-05 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0026_alter_blogpost_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=255, verbose_name='Título')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('read_time', models.PositiveIntegerField(default=5, verbose_name='Tiempo de lectura (minutos)')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Política de Privacidad',
                'verbose_name_plural': 'Políticas de Privacidad',
                'ordering': ['-created_at'],
            },
        ),
    ]
